
# CONFIGURACION DEL SERVIDOR

server.port=8080
# CONFIGURACION BASE DE DATOS

spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

